### ISSUE TITLE
[问题] Paper1.20.1发送消息会出现两条

### ISSUE THREAD

**Issue by WalleoAndrew** [TrPlugins/TrChat#304]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

在聊天栏发送消息时会出现一条Minecraft原版消息和一条TrChat消息，我在其他子服（版本1.18）中发送消息时并未出现此现象

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32766
  Kether-Allow-Tolerance-Parser: true

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 服务器环境

服务器版本:
git-Paper-117 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 9bc70
e6)
插件列表:
CMI, CMILib, CoreProtect, LuckPerms, PlaceholderAPI, ProtocolLib, QuickShop, Residence, TrChat, TrMenu,Vault, ViaBackwards, ViaVersion
